<a href="https://colab.research.google.com/github/AbrahamMulat/TensorFlow-deep-learning-Exercise-and-Project/blob/main/00_TensorFlow_fundamental_exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exercises

1. Create a **vector**, **scalar**,**matrix** and **tensor** with values of your choosing using `tf.constant()`.
2. Find the **shape**, **rank** and **size** of the tensors you created in 1.
3. Create two tensors containing random values between 0 and 1 with shape `[5, 300]`.
4. Multiply the two tensors you created in 3 using matrix multiplication.
5. Multiply the two tensors you created in 3 using dot product.
6. Create a tensor with random values between 0 and 1 with shape `[224, 224, 3]`.
7. Find the min and max values of the tensor you created in 6.
8. Create a tensor with random values of shape `[1, 224, 224, 3]` then squeeze it to change the shape to `[224, 224, 3]`.
9. Create a tensor with shape `[10]` using your own choice of values, then find the index which has the maximum value.
10. One-hot encode the tensor you created in 9.

# Solution

## 1. Create a **vector**, **scalar**, **matrix** and **tensor** with values of your choose using `tf.constants`.

In [1]:
import tensorflow as tf

print(tf.__version__)

2.8.2


In [2]:
# Create a scalar: a scalar is just a number with no dimension (rank 0 tensor)
tensor1 = tf.constant(8)
print(tensor1)

tf.Tensor(8, shape=(), dtype=int32)


In [3]:
# Create a vector: a vector is a number with dimensions (1 dimensional tensor or rank 1 tensor)
tensor2 = tf.constant([12, 6])
print(tensor2)

tf.Tensor([12  6], shape=(2,), dtype=int32)


In [4]:
# Create a matrix: a matrix is a 2 dimensional array of numbers (rank 2 tensor).
tensor3 =  tf.constant([[1, 2],
                 [3, 4],
                 [6, 8]])
print(tensor3)

tf.Tensor(
[[1 2]
 [3 4]
 [6 8]], shape=(3, 2), dtype=int32)


In [5]:
# Create a tensor: a tensor is an n-dimensional array of numbers (where n can be any number) 
tensor4 = tf.constant([[[2, 3, 5],
                  [1, 7, 8]],
                 [[3, 12, 80],
                  [11, 12, 13]]])
print(tensor4)

tf.Tensor(
[[[ 2  3  5]
  [ 1  7  8]]

 [[ 3 12 80]
  [11 12 13]]], shape=(2, 2, 3), dtype=int32)


## 2. Find the **shape**, **rank** and **size** of the tensors you created in 1.

In [6]:
# 1 find the shape, rank and size of a scalar (tensor1)
print(f"The shape of tensor1 (scalar) is :{tensor1.shape}")
print(f"The rank of tensor1 is: {tensor1.ndim}")
print(f"The size of tensor1 is: {tf.size(tensor1)}")

The shape of tensor1 (scalar) is :()
The rank of tensor1 is: 0
The size of tensor1 is: 1


In [7]:
# 2. Find the shape, rank and size of tensor2 (tensor2 is a vector)
print(f"The shape of tensor2 (vector) is :{tensor2.shape}")
print(f"The rank of tensor2 is: {tensor2.ndim}")
print(f"The size of tensor2 is: {tf.size(tensor2)}")

The shape of tensor2 (vector) is :(2,)
The rank of tensor2 is: 1
The size of tensor2 is: 2


In [8]:
# 3. Find the shape, rank and size of tensor3 (tensor3 is a matrix)
print(f"The shape of tensor3 (vector) is :{tensor3.shape}")
print(f"The rank of tensor3 is: {tensor3.ndim}")
print(f"The size of tensor3 is: {tf.size(tensor3)}")

The shape of tensor3 (vector) is :(3, 2)
The rank of tensor3 is: 2
The size of tensor3 is: 6


In [10]:
# 3. Find the shape, rank and size of tensor4 (tensor4 is a tensor)
print(f"The shape of tensor4 is :{tensor4.shape}")
print(f"The rank of tensor4 is: {tensor4.ndim}")
print(f"The size of tensor4 is: {tf.size(tensor4)}")

The shape of tensor4 is :(2, 2, 3)
The rank of tensor4 is: 3
The size of tensor4 is: 12


## 3. Create two tensors containing random values between 0 and 1 with shape `[5, 300]`.

In [13]:
tensor_5 = tf.random.uniform(shape=(5, 300))
tensor_6 = tf.random.uniform(shape=(5, 300))

print(f"{tensor_5} \n The shape of tensor_5 is: {tensor_5.shape}\n")
print(f"{tensor_6} \n The shape of tensor_6 is: {tensor_6.shape}")

[[0.770378   0.0119611  0.3197328  ... 0.2718172  0.19470847 0.604447  ]
 [0.22896862 0.17694116 0.9605558  ... 0.5905459  0.9574919  0.26937437]
 [0.6234163  0.5751046  0.41903925 ... 0.28773177 0.6582234  0.99332666]
 [0.11255097 0.5774727  0.31840205 ... 0.47999418 0.54973114 0.50827336]
 [0.92333114 0.38095903 0.7601987  ... 0.99880993 0.08303642 0.1241529 ]] 
 The shape of tensor_5 is: (5, 300)

[[0.37391198 0.42946243 0.1957022  ... 0.00119197 0.02767551 0.9653696 ]
 [0.60799086 0.61131954 0.71627724 ... 0.65106153 0.64819837 0.2062583 ]
 [0.11828542 0.76687765 0.18194902 ... 0.8711387  0.2939273  0.24595165]
 [0.7701591  0.60878134 0.23884976 ... 0.6033416  0.45594144 0.28359854]
 [0.04891169 0.6505923  0.61283064 ... 0.05361021 0.07390046 0.06227589]] 
 The shape of tensor_6 is: (5, 300)


## 4. Multiply the two tensors you created in 3 using **matrix multiplication**.

In [14]:
# Multiply the two tensors in 3: This won't work (shape mismatch)
tf.matmul(tensor_5, tensor_6)

InvalidArgumentError: ignored

In [21]:
# In order to mutlipy two matrix, the number of columns of the first matrix must be equal with the number of rows of the second matrix.
# to do that, we can transpose either tensor by using tf.ranspose or reshape one of the tensors.
result_1 = tf.matmul(tf.transpose(tensor_5), tensor_6)
result_2 = tf.matmul(tensor_5, tf.transpose(tensor_6))
print(f"The product of the two tensors after transposing tensor_5 is: \n {result_1}\n")
print(f"The shape of result_1 is: {result_1.shape}\n")
print(f"The product of the two tensors after transposing tensor_6 is: \n {result_2}\n")
print(f"The shape of result_2 is: {result_2.shape}")

The product of the two tensors after transposing tensor_5 is: 
 [[0.6328493  1.6181365  1.020928   ... 0.81047964 0.472528   1.033677  ]
 [0.6434567  1.1537429  0.605112   ... 0.98504627 0.5755097  0.37698537]
 [1.0355301  1.7342883  1.3687637  ... 1.223663   0.9559983  0.7474867 ]
 ...
 [0.91324204 1.6404321  1.2552902  ... 0.9786068  0.76754755 0.6533046 ]
 [1.1602503  1.5624192  1.025888   ... 1.5331494  1.0762848  0.70842147]
 [0.9048071  1.5762213  0.6894588  ... 1.3547434  0.72422004 1.0352631 ]]

The shape of result_1 is: (300, 300)

The product of the two tensors after transposing tensor_6 is: 
 [[82.235565 79.302444 78.51733  80.99044  76.96838 ]
 [77.91546  75.856    76.8821   79.94522  72.53163 ]
 [77.04551  76.38078  75.04396  77.17406  70.80564 ]
 [78.295006 79.48138  79.46156  79.445206 77.027534]
 [78.66778  77.031586 81.40069  82.23641  74.461174]]

The shape of result_2 is: (5, 5)


## 5. Multiply the two tensors you creates in 3 using **dot product**



In [23]:
# matrix multiplication using dot product
tf.tensordot(tensor_5, tf.transpose(tensor_6), axes=1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[82.235565, 79.302444, 78.51733 , 80.99044 , 76.96838 ],
       [77.91546 , 75.856   , 76.8821  , 79.94522 , 72.53163 ],
       [77.04551 , 76.38078 , 75.04396 , 77.17406 , 70.80564 ],
       [78.295006, 79.48138 , 79.46156 , 79.445206, 77.027534],
       [78.66778 , 77.031586, 81.40069 , 82.23641 , 74.461174]],
      dtype=float32)>

## 6. Create a tensor with random values between 0 and 1 with shape `[224, 224, 3]`.

In [24]:
tensor_7 = tf.random.uniform(shape=[224, 224, 3])
tensor_7

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.41290987, 0.80813265, 0.6509409 ],
        [0.7815919 , 0.8612586 , 0.5880122 ],
        [0.8697505 , 0.33171666, 0.9658748 ],
        ...,
        [0.44347715, 0.98053837, 0.36819136],
        [0.18709111, 0.848019  , 0.8458408 ],
        [0.00991881, 0.9697925 , 0.1005199 ]],

       [[0.02803195, 0.6266966 , 0.07868004],
        [0.00443375, 0.3272121 , 0.8595127 ],
        [0.4873767 , 0.26367676, 0.71990526],
        ...,
        [0.43814003, 0.23882282, 0.60826576],
        [0.2980957 , 0.16906619, 0.33049357],
        [0.33711517, 0.5569085 , 0.39855206]],

       [[0.90561306, 0.7819499 , 0.05615127],
        [0.8093798 , 0.87831223, 0.35902107],
        [0.90479267, 0.63742363, 0.39805305],
        ...,
        [0.32724702, 0.2996117 , 0.7814727 ],
        [0.39414513, 0.94698226, 0.19410133],
        [0.9191656 , 0.14255309, 0.20843852]],

       ...,

       [[0.96003056, 0.14111364, 0.25107872],
        [0.87

## 7. Find the min and max values of the tensor you created in 6.


In [25]:
# Find the minimum value of tensor_7
min_tensor_7 = tf.math.reduce_min(tensor_7)
print(f"The minimum value of tensor_7 is: {min_tensor_7}")

# Find the maximum value of tensor_7
max_tensor_7 = tf.math.reduce_max(tensor_7)
print(f"The maximum value of tensor_7 is: {max_tensor_7}")

The minimum value of tensor_7 is: 1.9311904907226562e-05
The maximum value of tensor_7 is: 0.99998939037323


## 8. Create a tensor with random values of shape `[1, 224, 224, 3]` then **squeeze** it to change the shape to `[224, 224, 3]`.

In [27]:
# Create a tensor with shape [1, 224, 224, 3]
unsqueezed_tensor = tf.random.Generator.from_seed(42)
unsqueezed_tensor = unsqueezed_tensor.normal(shape=(1, 224, 224, 3))
print(f"Unsqueezed Tensor \n{unsqueezed_tensor} \n The shape before squeezing is: {unsqueezed_tensor.shape}\n")

# Squeeze the tensor to change the shape to [224, 224, 3]
squeezed_tensor = tf.squeeze(unsqueezed_tensor)
print(f"Squeezed Tensor \n{squeezed_tensor} \n The shape after squeezing is: {squeezed_tensor.shape}")

Unsqueezed Tensor 
[[[[-0.7565803  -0.06854702  0.07595026]
   [-1.2573844  -0.23193765 -1.8107855 ]
   [ 0.09988727 -0.50998646 -0.7535806 ]
   ...
   [ 0.07099114 -0.5095768   0.3482001 ]
   [ 0.15985982 -1.9042184   0.9690504 ]
   [ 0.16251186 -0.07330751 -0.36059096]]

  [[ 0.18739441 -0.73353654  1.2104433 ]
   [ 1.5603006  -0.48115277  0.6335167 ]
   [-0.5612103   0.06994031  1.6807096 ]
   ...
   [-1.9460295  -0.7977275   0.03092833]
   [ 0.8297488   0.12179119  1.0506108 ]
   [-1.3097638   0.92536974 -1.1787732 ]]

  [[-0.21711825 -0.73974085 -1.3077081 ]
   [-0.7502274  -0.37715855 -0.30130875]
   [ 1.0943383   0.255803    0.8011465 ]
   ...
   [-0.32833767 -0.7794747   0.20049337]
   [-0.09002841  0.07243238 -0.81940895]
   [ 0.3171264  -1.6143695  -1.6824652 ]]

  ...

  [[-0.41068986 -0.3995463   0.16299413]
   [-0.82463205  1.1320542   0.43792698]
   [-0.7639474  -1.1266301  -0.7207727 ]
   ...
   [-0.8531011  -0.53761154 -0.32857296]
   [ 0.9262249  -1.2425404  -0.6993741

## 9. Create a tensor with shape `[10]` using your own choice of values, then find the index which has the **maximum value**.

In [28]:
tensor_10 = tf.constant([1, 2, 3, 100, 4, 5, 0, 6, 7, 8])

# Find the index which has the maximum value
max_index = tf.math.argmax(tensor_10)

print(f"The index which has the maximum value is: {max_index}")
print(f"The maximum value is: {tensor_10[max_index]}")

# Find the index which has the minimum value
min_index = tf.math.argmin(tensor_10)

print(f"The index which has the minimum value is: {min_index}")
print(f"The minimum value is: {tensor_10[min_index]}")

The index which has the maximum value is: 3
The maximum value is: 100
The index which has the minimum value is: 6
The minimum value is: 0


## 10. **One-hot** encode the tensor you created in 9.

In [29]:
# One-hot encode tensor_10
tf.one_hot(tensor_10, depth=10)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]], dtype=float32)>